#!/bin/bash
export LANG=en_US.UTF-8
export LC_ALL=en_US
export PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]}): '
set -x
if grep -q stack /etc/passwd; then
    find /var -xdev -user stack -exec chown "$OUTER_UID" '{}' ';'
    usermod -o -u "$OUTER_UID" stack
else
    useradd -o -U -u "$OUTER_UID" \
	-d /opt/stack -m \
	-s /bin/bash \
	stack
fi
if grep -q stack /etc/group; then
    find /var -xdev -group stack -exec chown "$OUTER_UID:$OUTER_GID" '{}' ';'
    groupmod -o -g "$OUTER_GID" stack
    usermod -g "$OUTER_GID" stack
fi

apt-get update
apt-get install -y tmux python-pip python-dev libssl-dev libxml2-dev \
    libxslt-dev libpq-dev libffi-dev gettext git ipmitool tftpd-hpa \
    syslinux syslinux-common python-numpy libmysqlclient-dev python-tox \
    rabbitmq-server python-openwsman

service rabbitmq-server start
#chmod 775 /var/run/screen
tmux new-session -d -n control -s dockonic "/bin/bash -l"
tmux set-option -t dockonic set-remain-on-exit on
for c in ironic-api ironic-conductor ironic-cli; do
    tmux new-window -n dockonic:$c "/opt/dockonic/$c"
done
tmux attach-session -t dockonic
