#!/bin/bash
set -e
cd /opt/stack/ironic
python setup.py develop
if [[ -f ironic/ironic.sqlite ]]; then
    su -c 'ironic-dbsync --config-file /opt/dockonic/ironic.conf upgrade' stack
else
    su -c 'ironic-dbsync --config-file /opt/dockonic/ironic.conf create_schema' stack
fi
echo >/tmp/.ironic-api
su -c 'ironic-api -v -d --config-file /opt/dockonic/ironic.conf' stack
