#!/bin/bash
set -e
cd /opt/stack/ironic
printf '%s' "Waiting on the Ironic API to start"
while [[ ! -f /tmp/.ironic-api ]] || ! ps aux |egrep -q '[i]ronic-api'; do
      printf '%s' '.'
      sleep 1
done
echo
su -c 'ironic-conductor -v -d --config-file /opt/dockonic/ironic.conf' stack
